SELECT ORDER#,
       CUSTOMER#,
       ORDERDATE,
       NVL2(SHIPDATE, SHIPDATE, '01-JAN-16') SHIPDATE,
       SHIPSTREET, 
       SHIPCITY, 
       SHIPSTATE,
       SHIPZIP,
       NVL(SHIPCOST, -1) SHIPCOST
FROM orders 
ORDER BY order#;
